name: fast-forward-merge

on:
  issue_comment:
    types:
      - created

jobs:
  fast-forward-merge:
    runs-on: ubuntu-latest
    # Only run this job when it's a comment in a pull request and the message is 'fast forward merge'
    if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, 'fast forward merge')
    steps:
      - uses: hmarr/debug-action@v2

      - uses: actions/github-script@v4
        with:
          script: |
            console.log(context)
            console.log(${{ toJSON(github) }})

      - name: Gets the pull request
        uses: actions/github-script@v4
        id: get-pr
        with:
          script: |
            const pr = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })

            console.log(pr.data)

            return pr.data
      
      - name: Get pull request Status API
        uses: octokit/request-action@v2.x
        id: get-pr-status-api
        with:
          route: GET /repos/{repo}/commits/{ref}/status
          repo: ${{ github.repository }}
          ref: ${{ fromJSON(steps.get-pr.outputs.result).head.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify pull request checks
        uses: actions/github-script@v4
        env:
          PR_MERGEABLE: ${{ fromJSON(steps.get-pr.outputs.result).mergeable }}
          PULL_NUMBER: ${{ fromJSON(steps.get-pr.outputs.result).number }}
          PR_STATUS_API_STATE: ${{ fromJSON(steps.get-pr-status-api.outputs.data).state }}
          PR_STATUS_API_STATUSES_LENGHT: ${{ fromJSON(steps.get-pr-status-api.outputs.data).statuses.lenght }}
          DATA: ${{ steps.get-pr-status-api.outputs.data  }}
        with:
          script: |
            console.log(process.env.PR_STATUS_API_STATE)
            console.log(process.env.DATA)

            const statusApi = JSON.parse(process.env.DATA)
            console.log(statusApi.state)
            console.log(statusApi.statuses.lenght)


            // If it's not mergeable, which means that the git branch cannot be marged to the base branch with no conflict or do not follows repositories policies
            if ((!process.env.PR_MERGEABLE || process.env.PR_MERGEABLE == "false") ||
            // Or if the status API state is not success or pending with no statuses (so no check for that pull request)
            ((process.env.PR_STATUS_API_STATE == "pending" && parseInt(process.env.PR_STATUS_API_STATUSES_LENGHT) > 0 ) || process.env.PR_STATUS_API_STATE != "success")) {
              const erroMsg = "Pull request not ready to be merged";

              github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `:x: ${erroMsg}`
              })

              core.setFailed(erroMsg);
            }

      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch everything
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Merge
        env:
          GIT_BASE_BRANCH: ${{ fromJSON(steps.get-pr.outputs.result).base.ref }}
          GIT_HEAD_BRANCH: ${{ fromJSON(steps.get-pr.outputs.result).head.ref }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          
          git checkout $GIT_BASE_BRANCH
          git merge --ff-only origin/$GIT_HEAD_BRANCH
          git push origin $GIT_BASE_BRANCH
